version: '3.8'

services:

  backend_frontend_env:

    build:
      context: .
      dockerfile: Dockerfile.backend_frontend

    container_name: backend_frontend_env_container

    networks:
      - app_network

    depends_on:
      - mongodb

    volumes: 
      - .:/app 


  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo_db

    container_name: mongodb_container

    volumes:
      - mongo_data:/opt/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: swcompetition
      MONGO_INITDB_ROOT_PASSWORD: swcompetition

    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
